apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: developer-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list","update","create","delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmap"]
  verbs: ["create"]