apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx

    resources:
      requests:
        memory: "1Gi"
        cpu: "1"

      limits:
        memory: "128Mi"
        cpu: "500m"